config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "categories#index"

  # get 'categories', to: 'categories#index'
  # get 'categories/new', to: 'categories#new'
  # get 'categories/:id', to: 'categories#show', as: :category
  # post 'categories', to: 'categories#create'
  # delete 'categories/:id', to: 'categories#destroy'

  # get 'categories/:category_id/bookmarks/new', to: 'bookmarks#new'

  resources :categories, except: %i[edit update] do
    resources :bookmarks, only: %i[new create show]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :comment, length: { minimum: 6 }
  validates :category_id, uniqueness: { scope: :recipe_id }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
  has_many :categories, through: :bookmarks
  validates :name, :description, presence: true
  validates :name, uniqueness: true
  validates :rating, numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 10.0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category = @category
    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unproccessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@bookmark.category), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:recipe_id, :comment)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :new, status: :unproccessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, status: :see_other
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Which recipe would you like to add to: <%= @category.name %>?</h1>

  <%= simple_form_for [@category, @bookmark], defaults: { wrapper_html: { class: "form-new" }, label_html: { class: "px-2" }} do |f| %>
    <%= f.association :recipe, placeholder: "choose a recipe from the dropdown" %>
    <%= f.input :comment, placeholder: "use this recipe all the time..." %>

    <%= f.submit "add recipe", class: "btn btn-primary btn-font-white" %>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path "banner.jpg" %>);">
  <div class="container">
    <h1>Cookbook</h1>
    <p>Save your favourite recipes</p>
  </div>
</div>

<div class="container">
  <div class="d-flex justify-content-between align-items-center py-3">
    <h2>List of categories</h2>
    <%= link_to "new category", new_category_path, class: "btn btn-primary btn-font-white" %>
  </div>
  <div class="card-container">
    <% @categories.each do |category| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
        <h3><%= link_to category.name.capitalize, category_path(category) %></h3>
        <p><%= category.recipes.length %> recipes</p>
        <%= link_to "🗑", category_path(category), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "card-category-icon" %>
      </div>
    <% end %>
  </div>

</div>

app/views/categories/new.html.erb
<div class="container">

  <h1>Add a new category to your cookbook</h1>

  <%= simple_form_for(@category) do |f| %>
    <%= f.input :name, placeholder: "breakfast dishes..." %>
    <%= f.submit "add category", class: "btn btn-primary btn-font-white" %>
  <% end %>
</div>



<%# <%= link_to 'back', categories_path %>

app/views/categories/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path "banner.jpg" %>);">
  <div class="container">
    <h1><%= @category.name %></h1>
  </div>
</div>

<div class="container">
  <div class="d-flex justify-content-between align-items-center py-3">
    <h2>Recipes</h2>
    <%= link_to "Add a recipe", new_category_bookmark_path(@category), class: "btn btn-primary btn-font-white" %>
  </div>
  <div class="card-container">

    <% @category.bookmarks.each do |bookmark| %>
    <div class="card-recipe">
      <%= image_tag bookmark.recipe.image_url %>
        <div class="p-3">
          <h3><%= bookmark.recipe.name.capitalize %></h3>
          <p><%= bookmark.recipe.description %></p>
        </div>
        <div class="card-recipe-infos">
          <h3>"<%= bookmark.comment %></h3>
          <h3><%= bookmark.recipe.rating %></h3>
          <%= link_to "🗑", bookmark_path(bookmark), data:
          { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "card-icon" %>
        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.jpg" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "home", root_path, class: "nav-link", style: "color: black;"  %>
          </li>
          <li class="nav-item">
            <%= link_to "new category", new_category_path, class: "nav-link", style: "color: black;" %>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>